### ISSUE TITLE
Refactor the serialization in JSON to include a unique GameID

### ISSUE THREAD

**Issue by sbordeyne** [cyian-1756/nsfw_game_updater#3]
Much of the code right now is reliant on the game name to find the right one, though, 2 games can have similar or even identical names. The code could be simplified if each game had its own unique ID. It would also allow for version controlling the games installed.

Example ID : 1234-4 : game 1234, version 4 (the version number should increase each time the game is updated in the database.

Also, it may be wise to host the database on a remote server, as an SQL database, as to not confuse the user with JSON files, which may be pretty big at some point.

**Comment by cyian-1756** [comment]
> Example ID : 1234-4 : game 1234, version 4 (the version number should increase each time the game is updated in the database.

An issue I can see here is that a lot of games don't version, maybe we could use game-dev-public builds

> Also, it may be wise to host the database on a remote server, as an SQL database, as to not confuse the user with JSON files, which may be pretty big at some point.

Yea we should move to sqlite or something and have the program check for an updated db every day or so

**Comment by sbordeyne** [comment]
It's kinda done with the db, every game has an unique ID.
