### ISSUE TITLE
Column showing version number OR current status

### ISSUE THREAD

**Issue by ghost** [cyian-1756/nsfw_game_updater#46]
E.g `In development`, `Abandoned`, `Completed` OR `1.2.6`,

**Comment by sbordeyne** [comment]
I'll add that, It can definitely help sort through games. Due to the way I coded the search engine, it'll work with it as well with "version:xxxxxxx" queries.

**Comment by ghost** [comment]
Oops, I meant to write a comment about how not every project adheres to the Semantic Versioning guidelines. E.g some projects use "episodes" rather than MAJOR/MINOR updates.

**Comment by sbordeyne** [comment]
I wanna say, fuck these projects. Harem uses a system like that (c7m3 : chapter 7 update 3) but you can turn it into a semantic version easily (7.3)

Episode y update x, we can turn it into version y.x

projects also use dates to version their projects, do we can turn that into ISO dates, and replace the `-` with a `.`

**Comment by sbordeyne** [comment]
added
